### ISSUE TITLE
[BUG] On controller, the dash direction is sometime misinterpreted

### ISSUE THREAD

**Issue by Elesh-Norn** [Alkaliii/pearlessential#2]
**Describe the bug**
When pushing into a direction, like north or south, despite the character walking towards it, when dash is pressed, the dash is performed in another direction.

**To Reproduce**
1. Walk in a direction, but slowly, not like a brute on the joystick.
2. Press the dash button.

**Expected behavior**
I expect the dash to work in the direction my character is facing.

**Screenshots**

https://github.com/Alkaliii/pearlessential/assets/29737733/df70e60f-2378-4738-85ed-f0ce59a1f61a

**Desktop (please complete the following information):**
 - OS: Windows
 - Game Version: 0.22

**Additional context**
Might be how you process input, and my controller have slight joystick drift. I have that happened because I was processing inputs in godot `_input(event)` instead of `_process(delta)`. `_input` will be called numerous time per frame, once per event afaik.

**Comment by Alkaliii** [comment]
Thanks for this report, I've made some changes to the calculation method for the new dash velocity and it seems to work on my end for now. Just wondering, did you switch the directional interpretation setting before using a controller?
