### ISSUE TITLE
[BUG] Entering first combat without equiping techniques, makes the game stuck.

### ISSUE THREAD

**Issue by Elesh-Norn** [Alkaliii/pearlessential#3]
**Describe the bug**
If you enter the first combat, without equipping anything, you get in a state where you cannot select something for your turn, and thus, get stuck

**To Reproduce**
1. Go to the room of the first fight, without equipping anything, get past the shelves.
2. Enter the combat

**Expected behavior**
I should not be able to enter the fight before having equipped techniques. Alternatively, if I have nothing equipped, it should pass my turn and my character should get killed.

**Screenshots**
![image](https://github.com/Alkaliii/pearlessential/assets/29737733/4f437e23-35b6-4fdd-ab71-2cd787c261d4)

**Desktop (please complete the following information):**
 - OS: Windows
 - Game Version: 0.22

**Comment by Alkaliii** [comment]
Next build should now skip the player's turn if they don't have any techs equipped, thanks
