### ISSUE TITLE
[BUG] In combat, attacks bound to right/left are inverted

### ISSUE THREAD

**Issue by Elesh-Norn** [Alkaliii/pearlessential#4]
**Describe the bug**
During combat, I can use techniques by using the d-pad or wasd.

However attacks bound to right and left are inverted.

**To Reproduce**
1. Equips techniques to right or left
2. Enter a combat
3. Try using them

**Expected behavior**
I'd expect the direction to match what's visually on screen.

**Screenshots**
Pressing right doesn't trigger Short slash but pressing left does
![image](https://github.com/Alkaliii/pearlessential/assets/29737733/957ccaad-33b3-4910-869e-1a5c9401a4f2)

**Desktop (please complete the following information):**
 - OS: Windows
 - Game Version: 0.22

**Comment by Alkaliii** [comment]
Added prompts directly to the item listings and straightened out the list
