### ISSUE TITLE
[BUG] Having 0 pearls does not prevent me from identifying techniques

### ISSUE THREAD

**Issue by Elesh-Norn** [Alkaliii/pearlessential#6]
**Describe the bug**
I have to analyse techniques in order to equip them. To do that I have to consume the pear currency. 
However, even though I have 0 in my inventory, I can still analyse them.

The display for pearl is also not actualized upon pearl consumption

**To Reproduce**
1. Go to the underground library with 1 perl
2. Pick up 2 techniques
3. Analyse 1, a pearl is consumed. It is removed from my inventory.
4. Get back to pause display, the pearl counter is still 1
5. Now Analyse a second.
6. The second is analysed despite 0 pearl.

**Expected behavior**
I expect to not be able to use analyse if I have 0 pearl.

**Screenshots**

https://github.com/Alkaliii/pearlessential/assets/29737733/bd75339e-1aee-42eb-a080-e8a5012bc4c2

![image](https://github.com/Alkaliii/pearlessential/assets/29737733/de2e6309-0bb7-4aa7-8ac0-184712dbe525)

**Desktop (please complete the following information):**
 - OS: Windows
 - Game Version: 0.2.2

**Comment by Alkaliii** [comment]
Fixed counter not updating. Since ShortSlash is the first starter skill, its research cost is intentionally set at zero, this is the same for the techniques found in the crates on the final floor of the tutorial room. I might tweak this later if I change up the item flow.
